Use BOM encoding to remove mark from start of file on windows
mrc-ide/specio pull request #12
Opened 2019-08-09 11:34 UTC by r-ash

This PR will
* Use `UTF-8-BOM` encoding when calling `read.csv` to strip byte order mark on windows machines

This isn't tested as I can't think of a way of writing a good test for this which would fail on a Linux machine. As it is a simple fix I figured it would be okay this case? I can try and add a test if you feel strongly otherwise.

Fixes #10

2019-08-09 13:51 UTC, richfitz approved these changes

2019-08-09 13:52 UTC, richfitz requested changes
actually, going back on my approval!

If we're using drat for distribution you need to bump the version number (and ideally add a news bullet)

2019-08-09 13:57 UTC, r-ash commented
Thanks, updated that version number now

2019-08-12 07:45 UTC, richfitz approved these changes

2019-08-12 07:45 UTC, merged